# Generated by Django 4.0.5 on 2022-06-14 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Vacantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo_vacante', models.CharField(max_length=100)),
                ('descripcion_vacante', models.CharField(max_length=500)),
                ('fecha_publicacion', models.DateTimeField(verbose_name='fecha de publicación')),
            ],
        ),
        migrations.CreateModel(
            name='DatosComplentariosVacantes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('salario', models.CharField(max_length=80)),
                ('ciudad', models.CharField(max_length=30)),
                ('vacantes', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vacantes')),
            ],
        ),
    ]
